# Release workflow with test gates
# Only releases when tests and build pass

name: Release

env:
  PLUGIN_NAME: blogseq

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  # Test job (required before release)
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Type checking
        run: pnpm typecheck
      - name: ESLint
        run: npx eslint src --max-warnings 0
      - name: Run tests
        run: pnpm test --run
      - name: Generate coverage
        run: pnpm test:coverage

  # Build job (required before release)
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build plugin
        run: pnpm build

  # Release job (only runs if test and build pass)
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: [test, build]
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build plugin
        run: pnpm build

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
